version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  go-service:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - dynamodb-local
